CREATE TABLE nominations
(
    RUN_TIME TIMESTAMP,
    TIME_INTERVAL TIMESTAMP,
    MKT_TYPE VARCHAR(10),
    BID_ID INTEGER,
    RESOURCE_NAME VARCHAR(50),
    REGION_NAME VARCHAR(50),
    ZONE_ID VARCHAR(50),
    PARTICIPANT_ID VARCHAR(50),
    SELF_SCHED_MW DECIMAL(7,2)
);
